#!/usr/bin/env bash
# Losslessness proof for docs/archive/CHANGELOG-through-2026-09-21.md — generated by methodology_trim.py v1.5.0.
#
# Self-contained and FROZEN: it embeds the record grammar it was written against, so a later change
# to the trimmer cannot silently change what this shard's proof means. Re-derives L1 (records-zone
# concatenation), L2 (zone pinning) and L3 (record partition). Exits non-zero on failure.
# Run it; do not trust a digest. The last hand-published digest for this repo is not reproducible
# from the artifacts it describes, which is the whole reason this file exists.
#
# NOTE: file contents are read by python, never through $(...) — command substitution strips
# trailing newlines, which silently truncates the LAST record and fails L1/L3 on a correct trim.
# That is not hypothetical: it is what the first version of this script did.
set -u
cd "$(git rev-parse --show-toplevel)" || exit 3
LIVE=CHANGELOG.md
SHARD=docs/archive/CHANGELOG-through-2026-09-21.md
TRIM_SHA="$(git log --diff-filter=A -1 --format=%H -- "$SHARD" 2>/dev/null)"
export LIVE SHARD TRIM_SHA
python3 - <<'PYEOF_VERIFY'
import os, re, subprocess, sys
from collections import Counter

RECORD_KIND = "heading"
RECORD_START = r"^### \d{4}-\d{2}-\d{2} · \["
FENCE_INFO = ""
FOOTER_MODE = "separator"
PREFIX = "../../"

# BL-27 fix 1: the same declared front-matter fields assert_L2's reversal exception already knows
# about (design's regenerated-field table), so a line that changed ONLY inside one of these spans
# is not "lost" — every OTHER line still must survive verbatim, unchanged from before this fix.
REGEN_PATTERNS = []
REGEN = [re.compile(p) for p in REGEN_PATTERNS]

FENCE = re.compile(r"^(`{3,}|~{3,})(.*)$")
LINK = re.compile(r"\]\(([^)\s]*)\)")
SCHEME = re.compile(r"^[A-Za-z][A-Za-z0-9+.\-]*:")


def scan(lines):
    marker = None
    for i, raw in enumerate(lines):
        s = raw.rstrip("\r\n")
        inside = marker is not None
        m = FENCE.match(s)
        info = ""
        if marker is None:
            if m:
                marker = (m.group(1)[0], len(m.group(1)))
                info = m.group(2).strip()
        else:
            ch, n = marker
            if m and m.group(1)[0] == ch and len(m.group(1)) >= n and m.group(2).strip() == "":
                marker = None
        yield i, s, inside, info


def spans(line):
    r = []
    i = 0
    n = len(line)
    while i < n:
        if line[i] == "`":
            j = i
            while j < n and line[j] == "`":
                j += 1
            t = j - i
            k = j
            while k < n:
                if line[k] == "`":
                    mm = k
                    while mm < n and line[mm] == "`":
                        mm += 1
                    if mm - k == t:
                        r.append((i, mm))
                        i = mm
                        break
                    k = mm
                else:
                    k += 1
            else:
                break
            continue
        i += 1
    return r


def indomain(t):
    return bool(t) and not SCHEME.match(t) and not t.startswith(("#", "/", "../"))


def maplinks(text, fn):
    lines = text.splitlines(keepends=True)
    out = []
    for i, s, inside, _info in scan(lines):
        raw = lines[i]
        if inside or FENCE.match(s):
            out.append(raw)
            continue
        sp = spans(raw)

        def repl(m):
            if any(a <= m.start() < b for a, b in sp):
                return m.group(0)
            new = fn(m.group(1))
            return m.group(0) if new is None else "](" + new + ")"

        out.append(LINK.sub(repl, raw))
    return "".join(out)


def invert(text):
    def back(t):
        if not t.startswith(PREFIX):
            return None
        s = t[len(PREFIX):]
        return s if indomain(s) else None
    return maplinks(text, back)


def zones(text):
    lines = text.splitlines(keepends=True)
    starts, hrs = [], []
    for i, s, inside, info in scan(lines):
        if inside:
            continue
        if RECORD_KIND == "heading" and re.match(RECORD_START, s):
            starts.append(i)
        elif RECORD_KIND == "fence" and info == FENCE_INFO:
            starts.append(i)
        if s.strip() == "---":
            hrs.append(i)
    if not starts:
        return "".join(lines), [], ""
    foot = len(lines)
    if FOOTER_MODE == "separator":
        for i in [h for h in hrs if h > starts[-1]]:
            if "".join(lines[i + 1:]).strip():
                foot = i
                break
    recs = []
    for k, st in enumerate(starts):
        en = starts[k + 1] if k + 1 < len(starts) else foot
        recs.append("".join(lines[st:en]))
    return "".join(lines[:starts[0]]), recs, "".join(lines[foot:])


def show(ref, path):
    p = subprocess.run(["git", "show", "%s:%s" % (ref, path)], stdout=subprocess.PIPE)
    if p.returncode:
        sys.exit("verify: cannot read %s:%s" % (ref, path))
    return p.stdout.decode("utf-8")


def readf(path):
    with open(path, "r", encoding="utf-8", newline="") as fh:
        return fh.read()


LIVE, SHARD = os.environ["LIVE"], os.environ["SHARD"]
TRIM = os.environ["TRIM_SHA"]
if TRIM:
    before, after, shard = show(TRIM + "^", LIVE), show(TRIM, LIVE), show(TRIM, SHARD)
    origin = "the trim commit " + TRIM[:7]
else:
    before, after, shard = show("HEAD", LIVE), readf(LIVE), readf(SHARD)
    origin = "HEAD vs the working tree (trim not yet committed)"

bfront, br, bfoot = zones(before)
afront, ar, afoot = zones(after)
sfront, sr, _sfoot = zones(shard)
sr_inv = [invert(r) for r in sr]
fails = []
ran = []


def anchor(rec):
    # The record's own first content line — its heading for a heading-kind ledger, its first
    # key: value line for a fence-kind one. Used only to LABEL records in the report; nothing
    # below decides pass or fail from it.
    for ln in rec.splitlines():
        s = ln.rstrip()
        if s.strip() and not FENCE.match(s):
            return s.strip()
    return ""


# --- What the TRIM COMMIT introduced, MEASURED rather than assumed (BL-36) -------------------
#
# This script re-derives from git at commit granularity, and a commit may legitimately carry more
# than the trim: this repository's own close-out practice writes the trim's ledger entry, that
# session's other entries, and the archive move in one commit. Those extra records are new
# content. They were never in `before`, so they make no claim whatsoever about whether an
# archived record survived — and they must not be able to fail a losslessness proof.
#
# The shipped versions of this script skipped them POSITIONALLY, via a constant `INJECTED` baked
# in at generation time as `1 if trims_the_ledger else 0`. That is a 0/1 flag, not a count: it is
# structurally incapable of modelling a commit that lands two records instead of one, so every
# bundled trim failed by construction with zero data loss. Four of this repo's six shipped proofs
# failed exactly that way while an independent identity-keyed re-derivation measured 0 records
# missing at every trim (docs/audits/2026-08-15-bl36-archive-losslessness.md).
#
# So the injected set is measured HERE, from record content: the records present in
# `after + shard` and absent from `before`. This is a different function of the same three
# artifacts — never the difference L1/L3 are about to assert on — so it cannot make those
# assertions vacuous: delete an archived record and it is missing from `have` no matter what else
# the commit added. Occurrences are removed one-for-one, preserving order, so L1 still compares
# bytes in sequence and a REORDER is still a failure.
#
# It deliberately does NOT excuse a record EDITED inside the trim commit. Such a record's
# pre-trim bytes exist nowhere afterwards; it is reported as MISSING and the proof stays red,
# which is BL-27's judgement and is still correct — a real loss has that same shape.
# NAMES: `absent_records` / `added_records`, not the obvious `missing` / `added`. This is a flat
# script -- every binding here is a module global -- and L2's front-matter clause below already
# binds `missing` for its own, unrelated meaning (front-matter LINES that vanished). Calling this
# one `missing` silently rebinds it before L3 reads it, and because L2 usually finds nothing the
# rebind is to [], so L3 skips its own clause and reports a downstream symptom instead. That is
# not hypothetical: it is what the first build of this fix did, and the narrowed loss control
# caught it. Anything added here needs the same namespace check.
have = Counter(ar) + Counter(sr_inv)
added_records = list((have - Counter(br)).elements())
absent_records = list((Counter(br) - have).elements())


def drop_added(seq, remaining):
    out = []
    for r in seq:
        if remaining.get(r, 0) > 0:
            remaining[r] -= 1
        else:
            out.append(r)
    return out


still_to_drop = dict(Counter(added_records))
ar_cmp = drop_added(ar, still_to_drop)
sr_cmp = drop_added(sr_inv, still_to_drop)

# --- L1: records-zone concatenation ---------------------------------------------------------
ran.append("L1")
rebuilt = ar_cmp + sr_cmp
if "".join(rebuilt) != "".join(br):
    fails.append("L1 records-zone concatenation is not byte-identical")

# --- L2: zone pinning. BOTH halves — footer AND front matter. -------------------------------
# The footer half is conditional (a ledger may legitimately have no footer); the front-matter
# half is not, and its absence is why an earlier version of this script printed "L1, L2 and L3
# hold" after running zero L2 assertions on both of this repo's real ledgers.
if bfoot.strip():
    ran.append("L2/footer")
    if afoot != bfoot:
        fails.append("L2 FOOTER is not byte-identical in the live file")
    if bfoot.strip() in shard or bfoot.strip() in invert(shard):
        fails.append("L2 FOOTER migrated into the shard")

ran.append("L2/front-matter")
# Front matter may GAIN declared blocks (the shard pointer, a new month heading); it may not lose
# or reword anything. Every non-blank line of the original must survive verbatim in the new front
# matter, and none of it may have travelled into the shard — UNLESS the only change is confined to
# a declared regenerated field's own value (BL-27 fix 1), the same exception assert_L2 already
# applies via its reversal loop. This is a narrower carve-out than assert_L2's, on purpose: it
# excuses a specific LINE only when it has a same-shaped partner line in the new front matter with
# identical bytes everywhere outside the declared span — an actual reword just outside the field's
# own parens still fails, same as an edit anywhere else in front matter.
def field_reversible(missing_line):
    for rx in REGEN:
        m = rx.search(missing_line)
        if not m:
            continue
        prefix, suffix = m.group(1), m.group(3)
        residue = missing_line[:m.start()] + missing_line[m.end():]
        for al in afront.splitlines():
            am = rx.search(al)
            if (am and am.group(1) == prefix and am.group(3) == suffix
                    and al[:am.start()] + al[am.end():] == residue):
                return True
    return False


# BL-28 fix: exact-line-set membership, not substring containment. `ln not in afront` tested
# whether `ln` occurs anywhere in the whole front-matter TEXT — an append-style edit that keeps
# the original line as a literal prefix of a new, longer line leaves that substring intact and
# reads as "found," so a real change to the line evaded detection. Comparing against the SET of
# exact lines in the new front matter closes that gap without touching field_reversible's own
# separate, correct line-by-line carve-out for the declared regenerated fields.
afront_lines = set(afront.splitlines())
missing = [ln for ln in bfront.splitlines()
           if ln.strip() and ln not in afront_lines and not field_reversible(ln)]
if missing:
    fails.append("L2 FRONT MATTER lost %d line(s), first: %r" % (len(missing), missing[0][:70]))
leaked = [ln for ln in bfront.splitlines()
          if ln.strip() and len(ln.strip()) > 24 and (ln in sfront or ln in "".join(sr))]
if leaked:
    fails.append("L2 FRONT MATTER leaked %d line(s) into the shard, first: %r"
                 % (len(leaked), leaked[0][:70]))

# --- L3: record partition ---------------------------------------------------------------------
ran.append("L3")
bad = None
if absent_records:
    # The only way a record from `before` fails to appear in `after + shard`: it was dropped, or
    # it was edited (in which case its pre-trim bytes are gone and an edited twin shows up in
    # `added_records`). Both are real; neither is excused. A count mismatch cannot occur here
    # without this firing first — len(rebuilt) is len(br) - len(absent_records) by construction —
    # so there is no separate count clause to state, and none that could ever run.
    fails.append("L3 %d record(s) present before the trim are MISSING from live+shard afterwards"
                 % len(absent_records))
else:
    bad = [i for i, (x, y) in enumerate(zip(br, rebuilt)) if x != y]
    if bad:
        fails.append("L3 record(s) out of order across the move: %s" % bad)

# BL-27 fix 2: a same-commit close-out bundling (this repo's own established practice — a
# session's own frontier receipt going status: pending -> complete, committed together with the
# archive write) makes position 0 (newest) legitimately differ between this commit's parent and
# itself. NOT an exemption — this stays a FAIL, loud, because a real loss can have this exact
# shape too — only a NOTE naming the known pattern, so a reader does not mistake it for an
# unqualified loss. Narrow on purpose: any OTHER record differing (bad != [0]) gets no such note.
#
# BL-36 re-expressed the gate in the new vocabulary. It was `bad == [0]` — the record-ALTERED
# shape under the old positional comparison — which is why it never fired for the busier ledger,
# whose bundling produced a count mismatch instead and so failed with no explanation at all
# (audit Finding #4). Additions no longer fail, so that half is gone; what remains is the edit,
# which now presents as exactly one MISSING record that was the frontier, paired with an added
# record carrying the same anchor. Still narrow on purpose: an edit to any other record, or one
# whose anchor changed, gets no such note.
notes = []
frontier_edit = (len(absent_records) == 1 and br and absent_records[0] == br[0]
                 and anchor(absent_records[0]) != ""
                 and any(anchor(a) == anchor(absent_records[0]) for a in added_records))
if fails and frontier_edit:
    notes.append(
        "the only missing record is the frontier one (position 0, newest), and an added record "
        "carries the same anchor -- matches a known, accepted pattern (BL-27): this repository's "
        "own practice bundles a session's close-out finalize edit into the same commit as an "
        "archive write, so the frontier record can legitimately differ between this commit's "
        "parent and itself. This does NOT confirm losslessness -- manually diff record 0 by hand "
        "to be sure it is a receipt finalize, not real data loss.")

print("source : %s" % origin)
print("records: %d before = %d retained + %d archived; added by the trim commit: %d"
      % (len(br), len(ar_cmp), len(sr_cmp), len(added_records)))
for m in absent_records:
    print("   MISSING: %s" % anchor(m)[:100])
for a in added_records:
    print("   added  : %s" % anchor(a)[:100])
print("checked: %s" % ", ".join(ran))
for f in fails:
    print("FAIL:", f)
for n in notes:
    print("NOTE:", n)
if fails:
    sys.exit(1)
# State what actually ran, never a blanket claim: on a ledger with no footer the footer clause is
# genuinely inapplicable, and saying "L2 holds" would be asserting something nothing tested.
print("OK: %s hold for %s" % (", ".join(ran), SHARD))
PYEOF_VERIFY
