#!/usr/bin/env bash
# Losslessness proof for docs/archive/CHANGELOG-through-2026-08-14.md — generated by methodology_trim.py v1.1.2.
#
# Self-contained and FROZEN: it embeds the record grammar it was written against, so a later change
# to the trimmer cannot silently change what this shard's proof means. Re-derives L1 (records-zone
# concatenation), L2 (zone pinning) and L3 (record partition). Exits non-zero on failure.
# Run it; do not trust a digest. The last hand-published digest for this repo is not reproducible
# from the artifacts it describes, which is the whole reason this file exists.
#
# NOTE: file contents are read by python, never through $(...) — command substitution strips
# trailing newlines, which silently truncates the LAST record and fails L1/L3 on a correct trim.
# That is not hypothetical: it is what the first version of this script did.
set -u
cd "$(git rev-parse --show-toplevel)" || exit 3
LIVE=CHANGELOG.md
SHARD=docs/archive/CHANGELOG-through-2026-08-14.md
INJECTED=1
TRIM_SHA="$(git log --diff-filter=A -1 --format=%H -- "$SHARD" 2>/dev/null)"
export LIVE SHARD INJECTED TRIM_SHA
python3 - <<'PYEOF_VERIFY'
import os, re, subprocess, sys

RECORD_KIND = "heading"
RECORD_START = r"^### \d{4}-\d{2}-\d{2} · \["
FENCE_INFO = ""
FOOTER_MODE = "separator"
PREFIX = "../../"

# BL-27 fix 1: the same declared front-matter fields assert_L2's reversal exception already knows
# about (design's regenerated-field table), so a line that changed ONLY inside one of these spans
# is not "lost" — every OTHER line still must survive verbatim, unchanged from before this fix.
REGEN_PATTERNS = []
REGEN = [re.compile(p) for p in REGEN_PATTERNS]

FENCE = re.compile(r"^(`{3,}|~{3,})(.*)$")
LINK = re.compile(r"\]\(([^)\s]*)\)")
SCHEME = re.compile(r"^[A-Za-z][A-Za-z0-9+.\-]*:")


def scan(lines):
    marker = None
    for i, raw in enumerate(lines):
        s = raw.rstrip("\r\n")
        inside = marker is not None
        m = FENCE.match(s)
        info = ""
        if marker is None:
            if m:
                marker = (m.group(1)[0], len(m.group(1)))
                info = m.group(2).strip()
        else:
            ch, n = marker
            if m and m.group(1)[0] == ch and len(m.group(1)) >= n and m.group(2).strip() == "":
                marker = None
        yield i, s, inside, info


def spans(line):
    r = []
    i = 0
    n = len(line)
    while i < n:
        if line[i] == "`":
            j = i
            while j < n and line[j] == "`":
                j += 1
            t = j - i
            k = j
            while k < n:
                if line[k] == "`":
                    mm = k
                    while mm < n and line[mm] == "`":
                        mm += 1
                    if mm - k == t:
                        r.append((i, mm))
                        i = mm
                        break
                    k = mm
                else:
                    k += 1
            else:
                break
            continue
        i += 1
    return r


def indomain(t):
    return bool(t) and not SCHEME.match(t) and not t.startswith(("#", "/", "../"))


def maplinks(text, fn):
    lines = text.splitlines(keepends=True)
    out = []
    for i, s, inside, _info in scan(lines):
        raw = lines[i]
        if inside or FENCE.match(s):
            out.append(raw)
            continue
        sp = spans(raw)

        def repl(m):
            if any(a <= m.start() < b for a, b in sp):
                return m.group(0)
            new = fn(m.group(1))
            return m.group(0) if new is None else "](" + new + ")"

        out.append(LINK.sub(repl, raw))
    return "".join(out)


def invert(text):
    def back(t):
        if not t.startswith(PREFIX):
            return None
        s = t[len(PREFIX):]
        return s if indomain(s) else None
    return maplinks(text, back)


def zones(text):
    lines = text.splitlines(keepends=True)
    starts, hrs = [], []
    for i, s, inside, info in scan(lines):
        if inside:
            continue
        if RECORD_KIND == "heading" and re.match(RECORD_START, s):
            starts.append(i)
        elif RECORD_KIND == "fence" and info == FENCE_INFO:
            starts.append(i)
        if s.strip() == "---":
            hrs.append(i)
    if not starts:
        return "".join(lines), [], ""
    foot = len(lines)
    if FOOTER_MODE == "separator":
        for i in [h for h in hrs if h > starts[-1]]:
            if "".join(lines[i + 1:]).strip():
                foot = i
                break
    recs = []
    for k, st in enumerate(starts):
        en = starts[k + 1] if k + 1 < len(starts) else foot
        recs.append("".join(lines[st:en]))
    return "".join(lines[:starts[0]]), recs, "".join(lines[foot:])


def show(ref, path):
    p = subprocess.run(["git", "show", "%s:%s" % (ref, path)], stdout=subprocess.PIPE)
    if p.returncode:
        sys.exit("verify: cannot read %s:%s" % (ref, path))
    return p.stdout.decode("utf-8")


def readf(path):
    with open(path, "r", encoding="utf-8", newline="") as fh:
        return fh.read()


LIVE, SHARD = os.environ["LIVE"], os.environ["SHARD"]
TRIM, INJ = os.environ["TRIM_SHA"], int(os.environ["INJECTED"])
if TRIM:
    before, after, shard = show(TRIM + "^", LIVE), show(TRIM, LIVE), show(TRIM, SHARD)
    origin = "the trim commit " + TRIM[:7]
else:
    before, after, shard = show("HEAD", LIVE), readf(LIVE), readf(SHARD)
    origin = "HEAD vs the working tree (trim not yet committed)"

bfront, br, bfoot = zones(before)
afront, ar, afoot = zones(after)
sfront, sr, _sfoot = zones(shard)
ar_cmp = ar[INJ:]
fails = []
ran = []

# --- L1: records-zone concatenation ---------------------------------------------------------
ran.append("L1")
rebuilt = list(ar_cmp) + [invert(r) for r in sr]
if "".join(rebuilt) != "".join(br):
    fails.append("L1 records-zone concatenation is not byte-identical")

# --- L2: zone pinning. BOTH halves — footer AND front matter. -------------------------------
# The footer half is conditional (a ledger may legitimately have no footer); the front-matter
# half is not, and its absence is why an earlier version of this script printed "L1, L2 and L3
# hold" after running zero L2 assertions on both of this repo's real ledgers.
if bfoot.strip():
    ran.append("L2/footer")
    if afoot != bfoot:
        fails.append("L2 FOOTER is not byte-identical in the live file")
    if bfoot.strip() in shard or bfoot.strip() in invert(shard):
        fails.append("L2 FOOTER migrated into the shard")

ran.append("L2/front-matter")
# Front matter may GAIN declared blocks (the shard pointer, a new month heading); it may not lose
# or reword anything. Every non-blank line of the original must survive verbatim in the new front
# matter, and none of it may have travelled into the shard — UNLESS the only change is confined to
# a declared regenerated field's own value (BL-27 fix 1), the same exception assert_L2 already
# applies via its reversal loop. This is a narrower carve-out than assert_L2's, on purpose: it
# excuses a specific LINE only when it has a same-shaped partner line in the new front matter with
# identical bytes everywhere outside the declared span — an actual reword just outside the field's
# own parens still fails, same as an edit anywhere else in front matter.
def field_reversible(missing_line):
    for rx in REGEN:
        m = rx.search(missing_line)
        if not m:
            continue
        prefix, suffix = m.group(1), m.group(3)
        residue = missing_line[:m.start()] + missing_line[m.end():]
        for al in afront.splitlines():
            am = rx.search(al)
            if (am and am.group(1) == prefix and am.group(3) == suffix
                    and al[:am.start()] + al[am.end():] == residue):
                return True
    return False


missing = [ln for ln in bfront.splitlines()
           if ln.strip() and ln not in afront and not field_reversible(ln)]
if missing:
    fails.append("L2 FRONT MATTER lost %d line(s), first: %r" % (len(missing), missing[0][:70]))
leaked = [ln for ln in bfront.splitlines()
          if ln.strip() and len(ln.strip()) > 24 and (ln in sfront or ln in "".join(sr))]
if leaked:
    fails.append("L2 FRONT MATTER leaked %d line(s) into the shard, first: %r"
                 % (len(leaked), leaked[0][:70]))

# --- L3: record partition ---------------------------------------------------------------------
ran.append("L3")
bad = None
if len(rebuilt) != len(br):
    fails.append("L3 record count %d != %d" % (len(rebuilt), len(br)))
else:
    bad = [i for i, (x, y) in enumerate(zip(br, rebuilt)) if x != y]
    if bad:
        fails.append("L3 record(s) not byte-identical across the move: %s" % bad)

# BL-27 fix 2: a same-commit close-out bundling (this repo's own established practice — a
# session's own frontier receipt going status: pending -> complete, committed together with the
# archive write) makes position 0 (newest) legitimately differ between this commit's parent and
# itself. NOT an exemption — this stays a FAIL, loud, because a real loss can have this exact
# shape too — only a NOTE naming the known pattern, so a reader does not mistake it for an
# unqualified loss. Narrow on purpose: any OTHER record differing (bad != [0]) gets no such note.
notes = []
if fails and bad == [0]:
    notes.append(
        "only the frontier record (position 0, newest) differs, across L1 and L3 -- matches a "
        "known, accepted pattern (BL-27): this repository's own practice bundles a session's "
        "close-out finalize edit into the same commit as an archive write, so the frontier "
        "record can legitimately differ between this commit's parent and itself. This does NOT "
        "confirm losslessness -- manually diff record 0 by hand to be sure it is a receipt "
        "finalize, not real data loss.")

print("source : %s" % origin)
print("records: %d before = %d retained + %d archived (%d entry injected by the trim)"
      % (len(br), len(ar_cmp), len(sr), INJ))
print("checked: %s" % ", ".join(ran))
for f in fails:
    print("FAIL:", f)
for n in notes:
    print("NOTE:", n)
if fails:
    sys.exit(1)
# State what actually ran, never a blanket claim: on a ledger with no footer the footer clause is
# genuinely inapplicable, and saying "L2 holds" would be asserting something nothing tested.
print("OK: %s hold for %s" % (", ".join(ran), SHARD))
PYEOF_VERIFY
