language: r
cache:
  - packages
  - github_packages
r:
    - release
    - devel
r_packages:
    - devtools
    - covr
    - rcmdcheck
matrix:
     include:
         - os: osx
           osx_image: xcode12.2
           fortran: false
addons:
  apt:
    packages:
      - libharfbuzz-dev
      - libfribidi-dev
script:
  - R CMD build . --compact-vignettes=gs+qpdf
  - R CMD check *tar.gz --as-cran
after_success:
  - R -e CODECOV_TOKEN 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_PAT
  keep_history: true
  local_dir: docs
  on:
    branch: master
env:
  - global:
    - CI=TRUE
    - LINTR_COMMENT_BOT=false
dist: xenial
os:
  - osx
    osx_image: xcode12.2
  - linux
