comment: false
codecov:
 token: 91d6f123-db2d-4177-ae13-35b926f8240f
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
