---
title: "Quick Example of Simulated Kinships with Partial Parentage"
author: "R. Mark Sharp"
date: "8/29/2021"
output: pdf_document
---

## Small Example

Not elegant at all


```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(kableExtra)
library(magrittr)
library(nprcgenekeepr)
library(stringi)

ped <- nprcgenekeepr::smallPed
simParent_1 <- list(id = "A", # nolint: object_name_linter
                    sires = c("s1_1", "s1_2", "s1_3"),
                    dams = c("d1_1", "d1_2", "d1_3", "d1_4"))
simParent_2 <- list(id = "B", # nolint: object_name_linter
                    sires = c("s1_1", "s1_2", "s1_3"),
                    dams = c("d1_1", "d1_2", "d1_3", "d1_4"))
simParent_3 <- list(id = "E", # nolint: object_name_linter
                    sires = c("A", "C", "s1_1"),
                    dams = c("d3_1", "B"))
simParent_4 <- list(id = "J", # nolint: object_name_linter
                    sires = c("A", "C", "s1_1"),
                    dams = c("d3_1", "B"))
simParent_5 <- list(id = "K", # nolint: object_name_linter
                    sires = c("A", "C", "s1_1"),
                    dams = c("d3_1", "B"))
simParent_6 <- list(id = "N", # nolint: object_name_linter
                    sires = c("A", "C", "s1_1"),
                    dams = c("d3_1", "B"))
allSimParents <- list(simParent_1, simParent_2, simParent_3,
                      simParent_4, simParent_5, simParent_6)

extractKinship <- function(simKinships, id1, id2, simulation) {
  ids <- dimnames(simKinships[[simulation]])[[1]]
  simKinships[[simulation]][seq_along(ids)[ids == id1],
                            seq_along(ids)[ids == id2]]
}

extractKValue <- function(kValue, id1, id2, simulation) {
  kValue[kValue$id_1 ==  id1 & kValue$id_2 == id2, paste0("sim_", simulation)]
}

```

This is the simulation. I am only printing out rows with kinship values that
vary.

```{r small-simulation}
set.seed(1)
n <- 10
simKinships <- createSimKinships(ped, allSimParents, pop = ped$id, n = n)
kValues <- kinshipMatricesToKValues(simKinships)
extractKValue(kValues, id1 = "A", id2 = "F", simulation = 1:n)
counts <- countKinshipValues(kValues)
counts$kinshipIds[1:3]
counts$kinshipValues[1:3]
counts$kinshipCounts[1:3]

stats_10 <- summarizeKinshipValues(counts)
nrow(stats_10[stats_10$sd > 0.0, ])

kable(stats_10[stats_10$sd > 0.0, ], longtable = TRUE) %>%
  kable_styling(latex_options = c("striped", "repeat_header"),
                repeat_header_method = "replace",
                repeat_header_text = "\\textit{(continued)}")

```
A larger simulation

```{r larger-simulation}
set.seed(1)
n <- 100
simKinships <- createSimKinships(ped, allSimParents, pop = ped$id, n = n)
kValues <- kinshipMatricesToKValues(simKinships)
extractKValue(kValues, id1 = "A", id2 = "F", simulation = 1:10)
counts <- countKinshipValues(kValues)
counts$kinshipIds[1:3]
counts$kinshipValues[1:3]
counts$kinshipCounts[1:3]

stats_100 <- summarizeKinshipValues(counts)
nrow(stats_100[stats_100$sd > 0.0, ])

kable(stats_100[stats_100$sd > 0.0, ], longtable = TRUE) %>%
  kable_styling(latex_options = c("striped", "repeat_header"),
                repeat_header_method = "replace",
                repeat_header_text = "\\textit{(continued)}")

```


A much larger simulation

```{r much-larger-simulation}
set.seed(1)
n <- 1000
simKinships <- createSimKinships(ped, allSimParents, pop = ped$id, n = n)
kValues <- kinshipMatricesToKValues(simKinships)
extractKValue(kValues, id1 = "A", id2 = "F", simulation = 1:10)
counts <- countKinshipValues(kValues)
counts$kinshipIds[1:3]
counts$kinshipValues[1:3]
counts$kinshipCounts[1:3]

stats_1000 <- summarizeKinshipValues(counts)
nrow(stats_1000[stats_1000$sd > 0.0, ])

kable(stats_1000[stats_1000$sd > 0.0, ], longtable = TRUE) %>%
  kable_styling(latex_options = c("striped", "repeat_header"),
                repeat_header_method = "replace",
                repeat_header_text = "\\textit{(continued)}")

```


Comparing the values and variation found for the various kinship values:

```{r comparison-10-1000}
stats_short <- stats_10[stats_10$sd > 0.0, ]
stats_long <- stats_1000[stats_1000$sd > 0.0, ]

if (any(stats_short$id_1 != stats_long$id_1) ||
      any(stats_short$id_2 != stats_long$id_2))
  cat("At least one row represents a different animal pair")

comprison <- data.frame(
  id_1 = stats_short$id_1,
  id_2 = stats_short$id_2,
  meanKin_short = stats_short$mean,
  meanKin_long = stats_long$mean,
  meanKinDelta = abs(stats_short$mean - stats_long$mean),
  sdKin_short = stats_short$sd,
  sdKin_long = stats_long$sd,
  sdKinDelta = abs(stats_short$sd - stats_long$sd)
)

kable(comprison, longtable = TRUE,
      digits = c(0, 0, 4, 4, 4, 4, 4, 4),
      caption = stri_c("Comparision of estimated kinships between simulations ",
                       "of 10 (short) and 1000 (long)")) %>%
  kable_styling(latex_options = c("striped", "repeat_header"),
                repeat_header_method = "replace",
                repeat_header_text = "\\textit{(continued)}",
                font_size = 10)

```

```{r comparison-100-1000}
stats_short <- stats_100[stats_100$sd > 0.0, ]
stats_long <- stats_1000[stats_1000$sd > 0.0, ]

if (any(stats_short$id_1 != stats_long$id_1) ||
      any(stats_short$id_2 != stats_long$id_2))
  cat("At least one row represents a different animal pair")

comprison <- data.frame(
  id_1 = stats_short$id_1,
  id_2 = stats_short$id_2,
  meanKin_short = stats_short$mean,
  meanKin_long = stats_long$mean,
  meanKinDelta = abs(stats_short$mean - stats_long$mean),
  sdKin_short = stats_short$sd,
  sdKin_long = stats_long$sd,
  sdKinDelta = abs(stats_short$sd - stats_long$sd)
)

kable(comprison, longtable = TRUE,
      digits = c(0, 0, 4, 4, 4, 4, 4, 4),
      caption = stri_c("Comparision of estimated kinships between simulations ",
                       "of 100 (short) and 1000 (long)")) %>%
  kable_styling(latex_options = c("striped", "repeat_header"),
                repeat_header_method = "replace",
                repeat_header_text = "\\textit{(continued)}",
                font_size = 10)
```
