## Copyright(c) 2017-2026 R. Mark Sharp
## This file is part of nprcgenekeepr
#'
#' Generate the issue #133 sibling fixture:
#' inst/extdata/examples/obfuscated_rhesus_mhc_ped_affected.csv
#'
#' A new sibling of inst/extdata/examples/obfuscated_rhesus_mhc_ped.csv
#' (design doc D5, docs/planning/issue133-affected-status-pedigree-diagram-
#' plan.md) -- reuses the same 375 individuals' id/sire/dam/sex/gen/birth/
#' exit/age columns verbatim (no re-obfuscation pass needed), and adds one
#' fabricated `affected` column so the pedigree diagram's new affected-
#' status shading (Slice 1) has a fixture to render against for live/e2e
#' verification (Phase 3E). RED-phase unit tests use small inline
#' data.frame() literals instead (see test_makePedigreeDiagramData.R /
#' test_makePedigreeMatingLayout.R) -- this fixture's only role is realistic
#' -scale live rendering.
#'
#' DISCLOSURE: the `affected` column is entirely synthetic, generated by the
#' seeded RNG below -- it is NOT drawn from any real medical/research
#' record, matching this project's existing synthetic-data disclosure
#' convention (vignettes/a2interactive.Rmd footnote 4, "This pedigree is
#' entirely synthetic -- constructed for this tutorial, not drawn from any
#' real colony's records"). Distribution: ~20% TRUE, ~70% FALSE, ~10% NA
#' (unknown affected status) -- a plausible disease-prevalence skew with
#' enough TRUE/NA rows to be visually obvious in a live smoke test.
#'
#' A new sibling file, not an in-place edit to the base fixture (D5): the
#' base obfuscated_rhesus_mhc_ped.csv is read by ~20 existing test files,
#' several of which pin its exact column/row counts -- adding a column
#' in-place risks silently perturbing tests unrelated to this feature.
#' Idempotent up to the fixed seed: re-running reproduces the identical
#' `affected` values every time.
#'
#' Run from the package root:
#'   Rscript data-raw/obfuscated_rhesus_mhc_ped_affected.R

set.seed(133L) ## issue #133 -- reproducible fabricated affected column

basePed <- read.csv(
  file.path("inst", "extdata", "examples", "obfuscated_rhesus_mhc_ped.csv"),
  stringsAsFactors = FALSE
)

affected <- sample(
  c(TRUE, FALSE, NA),
  size = nrow(basePed),
  replace = TRUE,
  prob = c(0.2, 0.7, 0.1)
)

affectedPed <- cbind(basePed, affected = affected)

write.csv(
  affectedPed,
  file.path("inst", "extdata", "examples",
            "obfuscated_rhesus_mhc_ped_affected.csv"),
  row.names = FALSE, na = "NA"
)
