## Copyright(c) 2017-2026 R. Mark Sharp
## This file is part of nprcgenekeepr
##
## BACKLOG.md: inst/WORDLIST has a large, long-standing gap -- devtools::check()'s
## spelling-check step (tests/spelling.R, spelling::spell_check_test(error = FALSE))
## fires a NOTE rather than a hard failure, so a genuinely new flagged word can drift
## in silently for many sessions before anyone notices the abbreviated `checking tests
## ... NOTE` line (found S521, 2026-08-11; see PROJECT_LEARNINGS.md). This guard makes
## the same check a hard testthat failure, matching the established
## test_pkgdown_reference_config.R precedent for drift that a soft NOTE won't catch.
##
## Known caveat: spelling::spell_check_package() scans the literal working directory,
## not a clean checkout. vignettes/*.md is .gitignore'd (regenerated by vignette
## builds) -- if a stale local build byproduct sits in vignettes/ from a prior
## rmarkdown::render()/devtools::build_vignettes() run, it can flag words (e.g.
## fragments of synthetic example IDs in rendered output) that never appear in the
## tracked .Rmd source and would never surface in a fresh checkout or CI. If this
## test fails locally with unfamiliar words, check `git status --porcelain
## vignettes/` for untracked .md/.html/.R byproducts before editing inst/WORDLIST --
## see Session 537 (2026-08-12) for the exact case that motivated this note.
##
## Locating the package source (a second Session 537 finding, found the hard way --
## an initial fix using a single ".." level looked right locally but still failed
## under a real R CMD check re-run; see PROJECT_LEARNINGS.md): testthat runs every
## test_that() block with the working directory set to the TEST FILE'S OWN
## directory (tests/testthat/), regardless of entry point (test_file(), test_dir(),
## or test_check() as used by R CMD check's own tests/testthat.R) -- confirmed by
## printing getwd() from inside a real test_that() block. spelling::spell_check_test()
## (tests/spelling.R) is a bare top-level script, NOT a testthat test, so it runs one
## level shallower (CWD = tests/) and its own sibling-`00_pkg_src` lookup uses only
## one "..". A testthat-based guard needs one more level. find_pkg_src() below
## reuses spelling's proven sibling-00_pkg_src strategy at the correct depth for a
## testthat context, with a devtools::test() fallback for local development.

find_pkg_src <- function() {
  ## R CMD check --as-cran: the source is preserved as a sibling 00_pkg_src dir,
  ## one level shallower than testthat's own per-test-file working directory.
  cand <- list.files("../../00_pkg_src", full.names = TRUE)
  if (length(cand) && file.exists(file.path(cand[1], "DESCRIPTION"))) {
    return(normalizePath(cand[1]))
  }
  ## Plain R CMD check (non --as-cran): sibling of a *.Rcheck directory.
  check_dir <- dirname(dirname(getwd()))
  if (grepl("[.]Rcheck$", check_dir)) {
    source_dir <- sub("[.]Rcheck$", "", check_dir)
    if (file.exists(file.path(source_dir, "DESCRIPTION"))) {
      return(normalizePath(source_dir))
    }
  }
  ## devtools::test()/testthat::test_file() from the source tree.
  cand <- tryCatch(testthat::test_path("..", ".."), error = function(e) NA_character_)
  if (!is.na(cand) && file.exists(file.path(cand, "DESCRIPTION"))) {
    return(normalizePath(cand))
  }
  NULL
}

test_that("inst/WORDLIST covers every word spell_check_package flags", {
  skip_if_not_installed("spelling")
  skip_on_cran()

  pkg_root <- find_pkg_src()
  skip_if(is.null(pkg_root), "could not locate the package source directory")

  result <- spelling::spell_check_package(pkg_root, vignettes = TRUE)
  flagged <- if (nrow(result) == 0) character(0) else as.character(result$word)

  expect_identical(
    flagged, character(0),
    info = paste0(
      length(flagged), " word(s) flagged by spelling::spell_check_package() are not ",
      "covered by inst/WORDLIST or a recognized dictionary:\n",
      paste(flagged, collapse = ", ")
    )
  )
})
