## Copyright(c) 2017-2026 R. Mark Sharp
## This file is part of nprcgenekeepr
##
## BACKLOG.md: inst/WORDLIST has a large, long-standing gap -- devtools::check()'s
## spelling-check step (tests/spelling.R, spelling::spell_check_test(error = FALSE))
## fires a NOTE rather than a hard failure, so a genuinely new flagged word can drift
## in silently for many sessions before anyone notices the abbreviated `checking tests
## ... NOTE` line (found S521, 2026-08-11; see PROJECT_LEARNINGS.md). This guard makes
## the same check a hard testthat failure, matching the established
## test_pkgdown_reference_config.R precedent for drift that a soft NOTE won't catch.
##
## Known caveat: spelling::spell_check_package() scans the literal working directory,
## not a clean checkout. vignettes/*.md is .gitignore'd (regenerated by vignette
## builds) -- if a stale local build byproduct sits in vignettes/ from a prior
## rmarkdown::render()/devtools::build_vignettes() run, it can flag words (e.g.
## fragments of synthetic example IDs in rendered output) that never appear in the
## tracked .Rmd source and would never surface in a fresh checkout or CI. If this
## test fails locally with unfamiliar words, check `git status --porcelain
## vignettes/` for untracked .md/.html/.R byproducts before editing inst/WORDLIST --
## see Session 537 (2026-08-12) for the exact case that motivated this note.
##
## Locating the package source (a second Session 537 finding, found the hard way --
## an initial fix using a single ".." level looked right locally but still failed
## under a real R CMD check re-run; see PROJECT_LEARNINGS.md): testthat runs every
## test_that() block with the working directory set to the TEST FILE'S OWN
## directory (tests/testthat/), regardless of entry point (test_file(), test_dir(),
## or test_check() as used by R CMD check's own tests/testthat.R) -- confirmed by
## printing getwd() from inside a real test_that() block. spelling::spell_check_test()
## (tests/spelling.R) is a bare top-level script, NOT a testthat test, so it runs one
## level shallower (CWD = tests/) and its own sibling-`00_pkg_src` lookup uses only
## one "..". A testthat-based guard needs one more level. find_pkg_src() below
## reuses spelling's proven sibling-00_pkg_src strategy at the correct depth for a
## testthat context, with a devtools::test() fallback for local development.

find_pkg_src <- function() {
  ## A candidate directory only counts as a real package SOURCE tree if it has both a
  ## DESCRIPTION file AND an inst/ subdirectory. DESCRIPTION alone is not sufficient -- an
  ## INSTALLED package (e.g. covr::package_coverage()'s R CMD INSTALL --install-tests copy)
  ## also retains a DESCRIPTION, but its inst/* contents get flattened into the package root at
  ## install time, so it has no inst/ subdirectory at all. Checking for inst/ is what tells a
  ## source tree apart from an installed one (Session 544, 2026-08-13 -- see the test_that()
  ## pair right below this function for the exact bug this closes).
  is_pkg_src <- function(dir) {
    file.exists(file.path(dir, "DESCRIPTION")) && dir.exists(file.path(dir, "inst"))
  }

  ## R CMD check --as-cran: the source is preserved as a sibling 00_pkg_src dir,
  ## one level shallower than testthat's own per-test-file working directory.
  cand <- list.files("../../00_pkg_src", full.names = TRUE)
  if (length(cand) && is_pkg_src(cand[1])) {
    return(normalizePath(cand[1]))
  }
  ## Plain R CMD check (non --as-cran): sibling of a *.Rcheck directory.
  check_dir <- dirname(dirname(getwd()))
  if (grepl("[.]Rcheck$", check_dir)) {
    source_dir <- sub("[.]Rcheck$", "", check_dir)
    if (is_pkg_src(source_dir)) {
      return(normalizePath(source_dir))
    }
  }
  ## devtools::test()/testthat::test_file() from the source tree.
  cand <- tryCatch(testthat::test_path("..", ".."), error = function(e) NA_character_)
  if (!is.na(cand) && is_pkg_src(cand)) {
    return(normalizePath(cand))
  }
  NULL
}

## Session 544 (2026-08-13) finding: test-coverage.yaml (covr::package_coverage(), which runs
## tests against an R CMD INSTALL --install-tests copy) fails this guard where R-CMD-check.yaml
## (a real R CMD check) does not. Root cause: under --install-tests, `inst/*` content is
## flattened into the installed package's own root (standard R install behavior) -- there is no
## `inst/` subdirectory there. find_pkg_src()'s branch 3 (the devtools::test() fallback) only
## checked for a DESCRIPTION file, which an INSTALLED package also has, so it accepted that
## directory as if it were the source tree. spelling::get_wordfile() then looked for
## <that-dir>/inst/WORDLIST, silently found nothing, and every already-whitelisted domain word
## got flagged as unknown -- reproduced locally byte-for-byte via a direct
## `R CMD INSTALL --install-tests` + `testthat::test_dir()` repro (146 flagged words, identical
## list to the CI failure). The 2 tests below pin find_pkg_src()'s source-vs-installed
## detection directly, independent of a full covr/R CMD INSTALL run.

test_that("find_pkg_src() rejects an installed-package layout with no inst/ directory", {
  ## Mimics what covr's --install-tests copy looks like: a DESCRIPTION file is present (an
  ## installed package always retains one), but inst/ is absent because its contents were
  ## flattened into the package root at install time. A correct find_pkg_src() must not accept
  ## this as a source tree.
  fake_root <- withr::local_tempdir()
  writeLines("Package: fakepkg", file.path(fake_root, "DESCRIPTION"))
  fake_testthat_dir <- file.path(fake_root, "tests", "testthat")
  dir.create(fake_testthat_dir, recursive = TRUE)

  withr::local_dir(fake_testthat_dir)
  expect_null(find_pkg_src())
})

test_that("find_pkg_src() accepts a real source-tree layout with inst/ present", {
  ## The genuine-source-tree counterpart of the fake above -- same DESCRIPTION + nested
  ## tests/testthat layout, but with inst/ present, as any real package source tree has. Must
  ## still resolve correctly so the fix above doesn't over-tighten find_pkg_src() and break the
  ## legitimate devtools::test()/R-CMD-check cases it already handles.
  fake_root <- withr::local_tempdir()
  writeLines("Package: fakepkg", file.path(fake_root, "DESCRIPTION"))
  dir.create(file.path(fake_root, "inst"), recursive = TRUE)
  fake_testthat_dir <- file.path(fake_root, "tests", "testthat")
  dir.create(fake_testthat_dir, recursive = TRUE)

  withr::local_dir(fake_testthat_dir)
  expect_equal(find_pkg_src(), normalizePath(fake_root))
})

test_that("inst/WORDLIST covers every word spell_check_package flags", {
  skip_if_not_installed("spelling")
  skip_on_cran()

  pkg_root <- find_pkg_src()
  skip_if(is.null(pkg_root), "could not locate the package source directory")

  result <- spelling::spell_check_package(pkg_root, vignettes = TRUE)
  flagged <- if (nrow(result) == 0) character(0) else as.character(result$word)

  expect_identical(
    flagged, character(0),
    info = paste0(
      length(flagged), " word(s) flagged by spelling::spell_check_package() are not ",
      "covered by inst/WORDLIST or a recognized dictionary:\n",
      paste(flagged, collapse = ", ")
    )
  )
})
