## Copyright(c) 2017-2026 R. Mark Sharp
## This file is part of nprcgenekeepr

#' Get demographic data
#'
#' This is a thin wrapper around \code{labkey.selectRows()}.
#'
#' @param colSelect (optional) a vector of comma separated strings specifying
#' which columns of a dataset or view to import
#' @return A data.frame containing LabKey demographic data with the columns
#' specified in the single parameter provided.
#'
#' @importFrom Rlabkey labkey.selectRows
#' @export
#' @examples
#' \dontrun{
#' ## Needs a connection to a LabKey server
#' library(nprcgenekeepr)
#' siteInfo <- getSiteInfo()
#' colSet <- siteInfo$lkPedColumns
#' source <- " generated by getDemographics: "
#' pedSourceDf <- tryCatch(getDemographics(colSelect = colSet),
#'   warning = function(wCond) {
#'     cat(paste0("Warning", source, wCond),
#'       name = "nprcgenekeepr"
#'     )
#'     return(NULL)
#'   },
#'   error = function(eCond) {
#'     cat(paste0("Error", source, eCond),
#'       name = "nprcgenekeepr"
#'     )
#'     return(NULL)
#'   }
#' )
#' }
#'
getDemographics <- function(colSelect = NULL) {
  siteInfo <- getSiteInfo()
  setLabKeyDefaults(siteInfo)
  demoDf <- labkey.selectRows(
    baseUrl = siteInfo$baseUrl, folderPath = siteInfo$folderPath,
    schemaName = siteInfo$schemaName, queryName = siteInfo$queryName,
    viewName = "", colSort = NULL, colFilter = NULL,
    containerFilter = NULL, colNameOpt = "fieldname",
    maxRows = NULL, colSelect = colSelect,
    showHidden = TRUE
  )
  demoDf
}
