## Copyright(c) 2017-2026 R. Mark Sharp
## This file is part of nprcgenekeepr

#' Get pedigree based on list of focal animals
#'
#' Reads the focal animal ids from the first column of a CSV or Excel file
#' and pulls the pedigree of their relatives from LabKey.
#'
#' @param fileName character vector of temporary file path of a CSV or Excel
#' file whose first column lists the focal animal ids.
#' @param sep column separator in CSV file
#' @return A data.frame (not a file) with columns \code{id}, \code{sex},
#' \code{birth}, \code{death}, \code{departure}, \code{dam} and
#' \code{sire}; the dates are character strings formatted as
#' \code{\%Y-\%m-\%d}. When the LabKey connection fails, an
#' \code{nprcgenekeeprErr} list with \code{failedDatabaseConnection} set is
#' returned instead.
#'
#' @importFrom futile.logger flog.debug
#' @importFrom readxl excel_format
#' @importFrom utils read.table
#' @export
#' @examples
#' library(nprcgenekeepr)
#' ## A successful call needs a LabKey connection and a file of focal ids.
#' ## This file does not exist, so the example shows the error handler.
#' source <- " generated by getFocalAnimalPed: "
#' tryCatch(getFocalAnimalPed(fileName = "breeding file.csv"),
#'   warning = function(wCond) {
#'     cat(paste0("Warning", source, wCond),
#'       name = "nprcgenekeepr"
#'     )
#'     return(NULL)
#'   },
#'   error = function(eCond) {
#'     cat(paste0("Error", source, eCond),
#'       name = "nprcgenekeepr"
#'     )
#'     return(NULL)
#'   }
#' )
getFocalAnimalPed <- function(fileName, sep = ",") {
  flog.debug(paste0("in getFocalAnimalPed\n"),
    name = "nprcgenekeepr"
  )
  focalAnimals <- readFocalAnimalIds(fileName, sep = sep)
  ped <- getLkDirectRelatives(ids = focalAnimals)
  if (is.null(ped)) {
    flog.debug(paste0(
      "in getFocalAnimalPed after getLkDirectRelatives, which ",
      "returned NULL.\n"
    ), name = "nprcgenekeepr")
    errorLst <- getEmptyErrorLst()
    errorLst$failedDatabaseConnection <-
      "Database connection failed: configuration or permissions are invalid."
    return(errorLst)
  }
  flog.debug(
    paste0(
      "in getFocalAnimalPed after getLkDirectRelatives, which ",
      "returned ped with ", nrow(ped), "rows.\n"
    ),
    name = "nprcgenekeepr"
  )
  names(ped) <- c("id", "sex", "birth", "death", "departure", "dam", "sire")
  ped <- ped[!is.na(ped$id), ]
  ped$birth <- format(ped$birth, format = "%Y-%m-%d")
  ped$death <- format(ped$death, format = "%Y-%m-%d")
  ped$departure <- format(ped$departure, format = "%Y-%m-%d")
  ped
}
