## Copyright(c) 2017-2026 R. Mark Sharp
## This file is part of nprcgenekeepr

#' Get the direct ancestors of selected animals
#'
#' Gets direct ancestors from labkey \code{study} schema and \code{demographics}
#' table.
#'
#' @inheritParams getParents
#' @return data.frame with pedigree structure having the records of the Ids
#' provided (the focal animals themselves) and all of their direct ancestors.
#' \code{NULL} is returned when the site configuration cannot be read or the
#' LabKey data cannot be fetched.
#'
#' @importFrom futile.logger flog.debug
#' @importFrom stringi stri_c
#' @family direct relatives
#' @export
#' @examples
#' \dontrun{
#' # Requires LabKey connection
#' library(nprcgenekeepr)
#' ## Have to a vector of focal animals
#' focalAnimals <- c("1X2701", "1X0101")
#' suppressWarnings(getLkDirectAncestors(ids = focalAnimals))
#' }
getLkDirectAncestors <- function(ids) {
  # getSiteInfo() is wrapped in tryCatch (mirroring the getDemographics guard
  # just below) so a present-but-malformed config file can never crash this
  # call site -- BACKLOG.md's "4 remaining unguarded getSiteInfo() call
  # sites". Only `error` is caught, not `warning`: a missing config file
  # WARNS but still returns usable defaults, which is not a failure.
  siteInfo <- tryCatch(getSiteInfo(),
    error = function(eCond) {
      flog.debug(
        stri_c("Error generated by getSiteInfo in getLkDirectAncestors: ",
                eCond),
        name = "nprcgenekeepr"
      )
      NULL
    }
  )
  if (is.null(siteInfo)) {
    return(NULL)
  }
  colSet <- siteInfo$lkPedColumns
  msgSource <- " generated by getDemographics in getLkDirectAncestors: "
  pedSourceDf <- tryCatch(getDemographics(colSelect = colSet),
    warning = function(wCond) {
      flog.debug(stri_c("Warning", msgSource, wCond),
        name = "nprcgenekeepr"
      )
      NULL
    },
    error = function(eCond) {
      flog.debug(stri_c("Error", msgSource, eCond),
        name = "nprcgenekeepr"
      )
      NULL
    }
  )
  if (is.null(pedSourceDf)) {
    return(NULL)
  }
  names(pedSourceDf) <- siteInfo$mapPedColumns
  generations <- walkPedigree(ids, pedSourceDf, "ancestors")
  ancestorsDf <- do.call(rbind, lapply(generations, function(generation) {
    pedSourceDf[pedSourceDf$id %in% generation, ]
  }))
  ancestorsDf[!duplicated(ancestorsDf$id), ]
}
