## Copyright(c) 2017-2026 R. Mark Sharp
## This file is part of nprcgenekeepr

#' Get the direct ancestors of selected animals
#'
#' Gets direct ancestors from labkey \code{study} schema and \code{demographics}
#' table.
#'
#' @inheritParams getParents
#' @return data.frame with pedigree structure having all of the direct ancestors
#' for the Ids provided.
#'
#' @importFrom futile.logger flog.debug
#' @importFrom stringi stri_c
#' @family direct relatives
#' @export
#' @examples
#' \dontrun{
#' # Requires LabKey connection
#' library(nprcgenekeepr)
#' ## Have to a vector of focal animals
#' focalAnimals <- c("1X2701", "1X0101")
#' suppressWarnings(getLkDirectAncestors(ids = focalAnimals))
#' }
getLkDirectAncestors <- function(ids) {
  siteInfo <- getSiteInfo()
  colSet <- siteInfo$lkPedColumns
  msgSource <- " generated by getDemographics in getLkDirectAncestors: "
  pedSourceDf <- tryCatch(getDemographics(colSelect = colSet),
    warning = function(wCond) {
      flog.debug(stri_c("Warning", msgSource, wCond),
        name = "nprcgenekeepr"
      )
      NULL
    },
    error = function(eCond) {
      flog.debug(stri_c("Error", msgSource, eCond),
        name = "nprcgenekeepr"
      )
      NULL
    }
  )
  if (is.null(pedSourceDf)) {
    return(NULL)
  }
  names(pedSourceDf) <- siteInfo$mapPedColumns
  parents <- ids
  len <- length(parents)
  ancestorsDf <- pedSourceDf[pedSourceDf$id %in% ids, ]
  while (len > 0L) {
    parents <- getParents(pedSourceDf, parents)
    len <- length(parents)
    if (len > 0L) {
      ancestorsDf <- rbind(ancestorsDf,
        pedSourceDf[pedSourceDf$id %in% parents, ],
        stringsAsFactors = FALSE
      )
    }
  }
  ancestorsDf[!duplicated(ancestorsDf$id), ]
}
