#' Get a normalized pedigree from a pluggable data source
#'
## Copyright(c) 2017-2026 R. Mark Sharp
## This file is part of nprcgenekeepr
#'
#' Internal data-source adapter for the pedigree fetch boundary used by
#' \code{getLkDirectRelatives()}. It isolates the brittle LabKey pull behind a
#' single seam and makes LabKey one pluggable provider, which also enables
#' offline, deterministic testing via the \code{"dataframe"} source.
#'
#' @return A normalized pedigree data.frame with columns \code{id}, \code{sex},
#' \code{birth}, \code{death}, \code{exit}, \code{dam}, and \code{sire}; or
#' \code{NULL} when a LabKey fetch fails (warning or error), preserving the
#' fail-soft contract \code{getLkDirectRelatives()} relies on.
#'
#' @param sourceType one of \code{"labkey"} (pull demographics via
#' \code{getDemographics()} and rename to the package's internal column names)
#' or \code{"dataframe"} (use a caller-supplied, already-normalized pedigree --
#' the offline/deterministic seam).
#' @param siteInfo (\code{"labkey"} only) site configuration list; defaults to
#' \code{getSiteInfo()}. Supplies \code{lkPedColumns} (the columns to pull) and
#' \code{mapPedColumns} (the one-to-one rename to the internal column names).
#' @param ped (\code{"dataframe"} only) an already-normalized pedigree
#' data.frame containing at least \code{id}, \code{sire}, and \code{dam}.
#' @import futile.logger
#' @importFrom stringi stri_c
#' @noRd
getPedigreeSource <- function(sourceType = c("labkey", "dataframe"),
                              siteInfo = NULL, ped = NULL) {
  sourceType <- match.arg(sourceType)
  if (sourceType == "dataframe") {
    if (is.null(ped) || !is.data.frame(ped)) {
      stop(
        "getPedigreeSource(): 'ped' must be a data.frame for ",
        "source = 'dataframe'.",
        call. = FALSE
      )
    }
    if (!all(c("id", "sire", "dam") %in% names(ped))) {
      stop(
        "getPedigreeSource(): 'ped' must contain columns id, sire, and dam.",
        call. = FALSE
      )
    }
    return(ped)
  }

  if (is.null(siteInfo)) {
    siteInfo <- getSiteInfo()
  }
  msgSource <- " generated by getDemographics in getPedigreeSource: "
  pedSourceDf <- tryCatch(getDemographics(colSelect = siteInfo$lkPedColumns),
    warning = function(cond) {
      flog.debug(stri_c("Warning", msgSource, cond),
        name = "nprcgenekeepr"
      )
      NULL
    },
    error = function(cond) {
      flog.debug(stri_c("Error", msgSource, cond),
        name = "nprcgenekeepr"
      )
      NULL
    }
  )
  if (is.null(pedSourceDf)) {
    return(NULL)
  }
  names(pedSourceDf) <- siteInfo$mapPedColumns
  pedSourceDf
}
